### ISSUE TITLE
Add password toggle into react text field

### ISSUE THREAD

**Issue by literat** [lmc-eu/spirit-design-system#260]

**Comment by joebochill** [comment]
Looks like you already have password toggles:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/29152776/193703654-d7666d9d-3e9e-438b-9012-c6aba2201232.png">

**Comment by literat** [comment]
> Looks like you already have password toggles

Hi,

thank you for your interest in our issue :-)

Password toggles exist only for `web` package implementation. See https://github.com/lmc-eu/spirit-design-system/blob/main/packages/web/src/js/Password.ts and https://github.com/lmc-eu/spirit-design-system/tree/main/packages/web/src/scss/components/TextField#password-toggle.

For React and `web-react` package there is no such implementation. See https://github.com/lmc-eu/spirit-design-system/blob/main/packages/web-react/src/components/TextField/TextField.tsx and https://spirit-design-system-storybook.netlify.app/?path=/docs/components-textfield--template.

We want to be able to use such functionality also in our React components when TextField is of type `password`.

Hope this is helpful.

**Comment by literat** [comment]
Already added.
