### ISSUE TITLE
web: Tooltip and Floating UI

### ISSUE THREAD

**Issue by literat** [lmc-eu/spirit-design-system#409]
We should be able to use Tooltip programmatically using Javascript API. In order to do so I suggest:

- use [Floating UI ](https://floating-ui.com/docs/tutorial) to handle the positioning of arrows
- The tooltip class should receive the configuration object through constructor
- The tooltip instance should be added automagically on `data-tooltip="<event-name>"`
- The position should be readable from `data-placement`
- The content is shown using `data-target`

**Comment by adamkudrna** [comment]
Are we OK with depending on Floating UI? It's lightweight, I know, but it's still a third-party dependency… I'm quite happy with [being lightweight too](https://github.com/lmc-eu/spirit-design-system/blob/main/packages/web/package.json#L51).

Could it be an optional dependency we are compatible with?

```json
  "dependencies": {
    "@csstools/normalize.css": "^12.0.0",
    "@lmc-eu/spirit-design-tokens": "^0.21.0",
    "@lmc-eu/spirit-icons": "^0.5.0"
  },
```

**Comment by adamkudrna** [comment]
That could be up to the user, I think.

**Comment by tomassychra** [comment]
It should be up to the user to install this dependency if they want to use the extended dropdown options. On our side, we should have some kind of conditional import, or the method itself, if it exists.

**Comment by literat** [comment]
- https://github.com/lmc-eu/spirit-design-system/pull/1246
- https://github.com/lmc-eu/spirit-design-system/pull/1237
- https://github.com/lmc-eu/spirit-design-system/pull/1197

**Comment by literat** [comment]
Released.
