### ISSUE TITLE
TextField: <input> element does not get "id" attribute

### ISSUE THREAD

**Issue by sustmi** [lmc-eu/spirit-design-system#585]
Since [the introduction of `TextFieldBase`](https://github.com/lmc-eu/spirit-design-system/commit/002a00fddb4689bb88020312e40bef9b8577ffc9), the the `id` prop is not passed to the `<input>` element: https://github.com/lmc-eu/spirit-design-system/blob/8942c3ecded8e3653f1c90c8a53a0f6c72d2a639/packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx#L19

You can see that `<ElementType>` gets `otherProps`, but `otherProps` does not contain `id` because `id` is explicitly destructured into separate variable here: https://github.com/lmc-eu/spirit-design-system/blob/8942c3ecded8e3653f1c90c8a53a0f6c72d2a639/packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx#L9-L10

That means that the following JSX code:
```jsx
<TextField
    id="my-id"
    // ...
/>
```
will generate the following markup (the HTML comment is mine):
```jsx
<div class="TextField">
    <label for="js-job-description-list-filter-salary" class="TextField__label">...</label>
    <input type="text" class="TextField__input" value=""> <!-- No "id" attribute here :( -->
</div>
```

**Comment by literat** [comment]
@sustmi Thanks for this issue 👍 This will be resolved in https://github.com/lmc-eu/spirit-design-system/pull/538/files#diff-f7ab3167a181f4c7920d65262f64644b820232f2384e1b7f7b3172cf8c003894R21.

I hope that @dlouhak will find the time to finalize this soon :-)

**Comment by adamkudrna** [comment]
#538 has been merged, closing this now.
