### ISSUE TITLE
JS event on data-toggle has sideeffect with Bootstrap 4

### ISSUE THREAD

**Issue by janicekt** [lmc-eu/spirit-design-system#662]
We have a problem with the fact that boostrap also has a lot of Javascript features on html element built on `data-toggle`. In version bootstrap 4, this creates a collision with Spirit. The newer boostrap 5 solves it by creating a special `data-bs-toggle` prefix (all data attributes has prefix `data-bs-*`). Don't you want to do it in spirit too, to avoid possible side-effects with other systems like bootstrap? The good prefix could be for example `data-spirit-*`

**Comment by literat** [comment]
Fixed by the release of version 1.
