### ISSUE TITLE
Missing GridSpan implementation in package web-react

### ISSUE THREAD

**Issue by tomasjanicek** [lmc-eu/spirit-design-system#978]
hi I can't find a React implementation of the GridSpan component anywhere.

twig implementation is here: https://github.com/lmc-eu/spirit-design-system/blob/main/packages/web-twig/src/Resources/components/Grid/GridSpan.twig

**Comment by literat** [comment]
https://jira.lmc.cz/browse/DS-431

**Comment by literat** [comment]
https://github.com/lmc-eu/spirit-design-system/pull/1028
